---
before_script:
- gem install hoe --no-document
- rake install_plugins check_extra_deps -t
language: ruby
notifications:
  email:
  - drbrain@segment7.net
rvm:
- 2.3
- 2.4
- 2.5
- 2.6
- 2.7
script: rake test check_manifest
install: "" # avoid running default bundler install

matrix:
  include:
  - rvm: "2.7"
    env: TRAVIS_MATRIX=pipeline
